### PR TITLE
Simplify code

### LINKED ISSUE #1: Regex Syntax Error
There's an extra slash on [this line](https://github.com/markhuge/hubot-github-compare/blob/master/scripts/compare.coffee#L18), which leads to something like this, which causes an error:

``` coffee
robot.respond ///
  hello
////i, (msg) ->
```

compiles to:

``` js
robot.respond(/hello/ / i, function(msg) {});
```

### PR DESCRIPTION
**Pull request by mal**
Closes #1 and #5
## Changes
- Massively simplify code while retaining functionality
- Remove need for dependency on coffee-script >= 1.7
- Bring docs into line with latest standards
- Allow syntax of requests to be a little more flexible
## Testing

**When no default user is set:**

```
Hubot> hubot compare me user/repo develop 1.0.1
Hubot> https://github.com/user/repo/compare/develop...1.0.1
Hubot> hubot compare hubot-github-compare develop master
-- nothing here, Hubot just ignores you --
```

**When default user is set to markhuge:**

```
Hubot> hubot compare me user/repo develop 1.0.1
Hubot> https://github.com/user/repo/compare/develop...1.0.1
Hubot> hubot compare hubot-github-compare develop master
Hubot> https://github.com/markhuge/hubot-github-compare/compare/develop...master
```

---

**Syntax test script**

``` coffee
pattern = /compare (?:me )?([\w-.\/]+) ([\w-.\/]+) (?:to )?([\w-.\/]+)/i

tests = [
  'compare me owner/repo treeish treeish',
  'compare me hubot/repo treeish tree/ish',
  'compare me hubot-anything/repo treeish v1.0.0',
  'compare me hubot treeish tree-ish',
  'compare owner/repo treeish treeish',
  'compare hubot/repo treeish tree/ish',
  'compare hubot-anything/repo treeish v1.0.0',
  'compare hubot treeish tree-ish',
  'compare owner/repo treeish to treeish',
  'compare hubot/repo treeish to tree/ish',
  'compare hubot-anything/repo treeish to v1.0.0',
  'compare hubot.js treeish to tree-ish',
  'compare hubot treeish to'
]

space = "                                             "
pad = (str) ->
  str + space.substr 0, 45 - str.length

for test in tests
  console.log pad(test), Array.prototype.slice.call(test.match(pattern) ? [], 1)
```

**Results:**

```
$ coffee test.coffee
compare me owner/repo treeish treeish         [ 'owner/repo', 'treeish', 'treeish' ]
compare me hubot/repo treeish tree/ish        [ 'hubot/repo', 'treeish', 'tree/ish' ]
compare me hubot-anything/repo treeish v1.0.0 [ 'hubot-anything/repo', 'treeish', 'v1.0.0' ]
compare me hubot treeish tree-ish             [ 'hubot', 'treeish', 'tree-ish' ]
compare owner/repo treeish treeish            [ 'owner/repo', 'treeish', 'treeish' ]
compare hubot/repo treeish tree/ish           [ 'hubot/repo', 'treeish', 'tree/ish' ]
compare hubot-anything/repo treeish v1.0.0    [ 'hubot-anything/repo', 'treeish', 'v1.0.0' ]
compare hubot treeish tree-ish                [ 'hubot', 'treeish', 'tree-ish' ]
compare owner/repo treeish to treeish         [ 'owner/repo', 'treeish', 'treeish' ]
compare hubot/repo treeish to tree/ish        [ 'hubot/repo', 'treeish', 'tree/ish' ]
compare hubot-anything/repo treeish to v1.0.0 [ 'hubot-anything/repo', 'treeish', 'v1.0.0' ]
compare hubot.js treeish to tree-ish          [ 'hubot.js', 'treeish', 'tree-ish' ]
compare hubot treeish to                      [ 'hubot', 'treeish', 'to' ]
```

### CODE REVIEW

File: scripts/compare.coffee [hunk 1]
```diff
@@ -1,28 +1,28 @@
...
 user = process.env.HUBOT_GITHUB_USER
+
 module.exports = (robot) ->
-  if user
-    robot.respond ///
-        compare\ me\ (:?#{user}\/)*([\w-]+)\ ([\w\.\/\\-]+)\s([\w\.\/\\-]+)
-      ////i, (msg) ->
-      msg.send "https://github.com/#{user}/#{msg.match[2]}/compare/#{msg.match[3]}...#{msg.match[4]}"
+  robot.respond /compare (?:me )?([\w-.\/]+) ([\w-.\/]+) (?:to )?([\w-.\/]+)/i, (msg) ->
+    [_, repo, from, to] = msg.match
```
Comment (markhuge) [inline scripts/compare.coffee:20]: This is a really smart use of the destructuring assignment. I'm probably going to end up refactoring a bunch of my other scripts to follow this pattern.

Comment (mal) [inline scripts/compare.coffee:20]: Hehe, thanks! Probably shouldn't take the credit though, my brain probably pinched it from something it saw in the ocean of GitHub! :grinning:

**Comment by markhuge** [comment]
@mal merged, added some tests and now available as hubot-github-compare@1.0.0

Thanks for your input!

**Comment by mal** [comment]
Cool, thanks for the plugin!
